webhook:
  image:
    repository: ghcr.io/deinstapel/kube-overlay-operator/webhook
    tag: edge
    pullPolicy: Always
  replicaCount: 1
  resources: {}
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  hostNetwork: true

sidecar:
  image:
    repository: ghcr.io/deinstapel/kube-overlay-operator/sidecar
    tag: edge
    pullPolicy: Always

replicaCount: 1
image:
  repository: ghcr.io/deinstapel/kube-overlay-operator/operator
  pullPolicy: Always
  tag: edge

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"

resources:          
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
