---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overlay-network-sidecar
rules:
- apiGroups:
  - network.deinstapel.de
  resources:
  - overlaynetworks
  verbs:
  - get
  - list
  - watch