# permissions for end users to view overlaynetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: overlaynetwork-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-overlay-operator
    app.kubernetes.io/part-of: kube-overlay-operator
    app.kubernetes.io/managed-by: kustomize
  name: overlaynetwork-viewer-role
rules:
- apiGroups:
  - network.deinstapel.de
  resources:
  - overlaynetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.deinstapel.de
  resources:
  - overlaynetworks/status
  verbs:
  - get
