apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-overlay-operator.fullname" . }}-webhook
  labels:
    app.kubernetes.io/component: "webhook"
    {{- include "kube-overlay-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/component: "webhook"
    {{- include "kube-overlay-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: "metrics"
    {{- include "kube-overlay-operator.labels" . | nindent 4 }}
  name: {{ include "kube-overlay-operator.fullname" . }}-metrics
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: "operator"
    {{- include "kube-overlay-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: "metrics"
    {{- include "kube-overlay-operator.labels" . | nindent 4 }}
  name: {{ include "kube-overlay-operator.fullname" . }}-webhook-metrics
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: "webhook"
    {{- include "kube-overlay-operator.selectorLabels" . | nindent 4 }}
