apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-overlay-operator.fullname" . }}-webhook
  labels:
    app.kubernetes.io/component: webhook
    {{- include "kube-overlay-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: webhook
      {{- include "kube-overlay-operator.selectorLabels" . | nindent 6 }}
  replicas: {{ coalesce .Values.webhook.replicaCount .Values.replicaCount }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: operator
        {{- with coalesce .Values.webhook.podAnnotations .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/component: webhook
        {{- include "kube-overlay-operator.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
      volumes:
      - name: webhook-cert
        secret:
          defaultMode: 420
          secretName: {{ .Release.Name }}-webhook-server-cert
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.webhook.hostNetwork }}
      containers:
      - name: kube-rbac-proxy
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
        args:
        - "--secure-listen-address=0.0.0.0:8443"
        - "--upstream=http://127.0.0.1:8080/"
        - "--logtostderr=true"
        - "--v=0"
        ports:
        - containerPort: 8443
          protocol: TCP
          name: https
      - command:
        - /manager
        args:
        - "--health-probe-bind-address=:8081"
        - "--metrics-bind-address=127.0.0.1:8080"
        env:
        - name: "SIDECAR_IMAGE"
          value: "{{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag | default .Chart.AppVersion }}"
        - name: "SIDECAR_PULL_POLICY"
          value: "{{ .Values.sidecar.image.pullPolicy }}"
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-cert
          readOnly: true
        image: "{{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
        name: operator
        securityContext:
          {{- toYaml (coalesce .Values.webhook.securityContext .Values.securityContext) | nindent 10 }}
        resources:
          {{- toYaml (coalesce .Values.webhook.resources .Values.resources) | nindent 12 }}
        {{- with (coalesce .Values.webhook.nodeSelector .Values.nodeSelector) }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with coalesce .Values.webhook.affinity .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with coalesce .Values.webhook.tolerations .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      serviceAccountName: {{ include "kube-overlay-operator.webhookServiceAccountName" . }}
      terminationGracePeriodSeconds: 60
---

