apiVersion: network.deinstapel.de/v1alpha1
kind: OverlayNetwork
metadata:
  labels:
    app.kubernetes.io/name: overlaynetwork
    app.kubernetes.io/instance: overlaynetwork-sample
    app.kubernetes.io/part-of: kube-overlay-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-overlay-operator
  name: overlaynetwork-sample
spec:
  # TODO(user): Add fields here
