apiVersion: network.deinstapel.de/v1alpha1
kind: OverlayNetwork
metadata:
  labels:
    app.kubernetes.io/name: overlaynetwork
    app.kubernetes.io/instance: overlaynetwork-sample
    app.kubernetes.io/part-of: kube-overlay-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-overlay-operator
  name: overlaynetwork-sample
spec:
  # UDP port for the network to go
  port: 5555
  # Network CIDR to allocate pod IPs from
  allocatableCIDR: 10.10.10.0/24
  # List of CIDRs that are reachable via the "router" Pods
  routableCIDRs:
  - 10.10.0.0/16
  - 192.168.2.1/0
